branch-defaults:
  master:
    environment: gear-dev
    group_suffix: null
environment-defaults:
  Downloads-dev:
    branch: null
    repository: null
  gear-dev:
    branch: null
    repository: null
global:
  application_name: gear
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Docker 18.09.9-ce
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
